#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/vendor/autoload.php')) {
    require __DIR__.'/vendor/autoload.php';
} else {
    require __DIR__.'/../../autoload.php';
}

$app = new Symfony\Component\Console\Application('Mailer', '0.1.0');

$app->add(new \Scalex\Mailer\Commands\InitCommand);
$app->add(new \Scalex\Mailer\Commands\NewCommand);
$app->add(new \Scalex\Mailer\Commands\SendCommand);

$app->run();
